name: flutter03_state
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

linter:
    rules:
      prefer_typing_uninitialized_variables: false
      prefer_const_constructors_in_immutables: false
      prefer_const_constructors: false
      avoid_print: false
      prefer_const_literals_to_create_immutables: false


